sonata_user:
    security_acl: true
    manager_type: orm # can be orm or mongodb
    profile:
        # Customize user portal menu by setting links
        menu:
            - { route: 'sonata_user_profile_edit', label: 'link_edit_profile', domain: 'SonataUserBundle'}
            - { route: 'sonata_user_profile_edit_authentication', label: 'link_edit_authentication', domain: 'SonataUserBundle'}

sonata_block:
    default_contexts: [admin]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.admin.block.search_result:
            contexts: [admin]

sonata_admin:
    title: Hasheado Admin
    title_logo: 'http://upload.wikimedia.org/wikipedia/commons/c/ce/Transparent.gif'
    security:
        handler: sonata.admin.security.handler.acl
    templates:
        layout:  HasheadoAdminBundle::hasheado_layout.html.twig
        dashboard: HasheadoAdminBundle:Core:dashboard.html.twig
        list: HasheadoAdminBundle:CRUD:list.html.twig
        edit: HasheadoAdminBundle:CRUD:edit.html.twig
        user_block: HasheadoAdminBundle:Block:account.html.twig
        search:              SonataAdminBundle:Core:search.html.twig
        search_result_block: SonataAdminBundle:Block:block_search_result.html.twig
    assets:
        stylesheets:
            - http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css
            - http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css
            - bundles/hasheadoadmin/css/bootstrap/bootstrap-datetimepicker.min.css
            - bundles/hasheadoadmin/css/bootstrap/dataTables.bootstrap.css
            - bundles/hasheadoadmin/css/vendor/AdminLTE/AdminLTE.css
            - bundles/hasheadoadmin/css/vendor/multiple.select/multiple-select.css
            - bundles/hasheadoadmin/js/vendor/select2/select2.css
            - bundles/hasheadoadmin/css/bootstrap/bootstrap3-wysihtml5.min.css
            - bundles/hasheadoadmin/css/admin.css

fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  admin

    group:
        group_manager: sonata.user.orm.group_manager                    # If you're using doctrine orm (use sonata.user.mongodb.user_manager for mongodb)

    service:
        user_manager: sonata.user.orm.user_manager                      # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)

    from_email:
        address:        noreply@adminbundle.com
        sender_name:    Hasheado Admin Bundle

doctrine:
    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        entity_managers:
            default:
                mappings:
                    SonataUserBundle: ~

swiftmailer:
    transport: mail

twig:
    form:
        resources:
            - 'HasheadoAdminBundle:Form:datepicker.html.twig'

parameters:
    sonata.user.admin.user.class: Hasheado\AdminBundle\Admin\UserAdmin
    sonata.user.admin.group.class: Hasheado\AdminBundle\Admin\GroupAdmin
