sonata_user:
    security_acl: true
    manager_type: orm # can be orm or mongodb
    profile:
        # Customize user portal menu by setting links
        menu:
            - { route: 'sonata_user_profile_edit', label: 'link_edit_profile', domain: 'SonataUserBundle'}
            - { route: 'sonata_user_profile_edit_authentication', label: 'link_edit_authentication', domain: 'SonataUserBundle'}

sonata_block:
    default_contexts: [admin]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]
        #sonata.block.service.text:
        #sonata.block.service.rss:
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)

sonata_admin:
    title: Hasheado Admin
    security:
        handler: sonata.admin.security.handler.acl
    templates:
        layout:  HasheadoAdminBundle::hasheado_layout.html.twig
        dashboard: HasheadoAdminBundle:Core:dashboard.html.twig
        list: HasheadoAdminBundle:CRUD:list.html.twig
    assets:
        stylesheets:
            - http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css
            - http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css
            - bundles/hasheadoadmin/css/bootstrap/dataTables.bootstrap.css
            - bundles/hasheadoadmin/css/vendor/AdminLTE/AdminLTE.css
            - bundles/hasheadoadmin/css/admin.css

fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  admin
    user_class:     Application\Sonata\UserBundle\Entity\User

    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager                    # If you're using doctrine orm (use sonata.user.mongodb.user_manager for mongodb)

    service:
        user_manager: sonata.user.orm.user_manager                      # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)

doctrine:
    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationSonataUserBundle: ~
                    SonataUserBundle: ~
